WITH GENERATION_1 AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
GENERATION_2 AS (
    SELECT e.ID 
    FROM ECOLI_DATA e 
    JOIN GENERATION_1 g1 ON e.PARENT_ID = g1.ID
),
GENERATION_3 AS (
    SELECT e.ID
    FROM ECOLI_DATA e
    JOIN GENERATION_2 g2 ON e.PARENT_ID = g2.ID
)

SELECT ID FROM GENERATION_3;