-- 코드를 작성해주세요
SELECT g3.ID
    FROM ECOLI_DATA g1
    LEFT JOIN ECOLI_DATA g2 ON g1.ID = g2.PARENT_ID
    LEFT JOIN ECOLI_DATA g3 ON g2.ID = g3.PARENT_ID
    WHERE g1.PARENT_ID IS NULL AND g3.ID is NOT NULL
        ORDER BY g3.ID ASC
    
    