WITH SEP_TO_OCT_FIVE_OR_MORE AS (
    SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE MONTH(START_DATE) BETWEEN 8 AND 10
        GROUP BY CAR_ID
        HAVING count(*) >= 5
)


SELECT MONTH(START_DATE) "MONTH", CAR_ID, count(*) "RECORDS"
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) BETWEEN 8 AND 10
    
    GROUP BY MONTH, CAR_ID
    HAVING RECORDS != 0
    
    AND CAR_ID IN (SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE MONTH(START_DATE) BETWEEN 8 AND 10
        GROUP BY CAR_ID
        HAVING count(*) >= 5)
    ORDER BY MONTH ASC, CAR_ID DESC
