-- 코드를 입력하세요


WITH DONE_UPPER_70 AS (
    SELECT WRITER_ID, sum(PRICE) 'TOTAL_SALES'
        FROM USED_GOODS_BOARD
            WHERE STATUS = 'DONE'
            GROUP BY WRITER_ID
            HAVING TOTAL_SALES >= 700000
    )
    
SELECT u.USER_ID, u.NICKNAME,  d70.TOTAL_SALES
    FROM USED_GOODS_USER u JOIN DONE_UPPER_70 d70
    ON u.USER_ID = d70.WRITER_ID
        ORDER BY d70.TOTAL_SALES ASC;
# 거래상태 -> DONE 인 것의 가격 합