-- 코드를 입력하세요
SELECT b.CATEGORY, sum(bs.SALES) "TOTAL_SALES"
    FROM BOOK_SALES bs JOIN BOOK b 
    ON bs.BOOK_ID = b.BOOK_ID
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
    GROUP BY b.CATEGORY
    ORDER BY b.CATEGORY ASC
    