SELECT fh.FLAVOR FROM FIRST_HALF fh
    JOIN (SELECT FLAVOR, sum(TOTAL_ORDER) TOTAL_ORDER
            FROM JULY
            GROUP BY FLAVOR) j on fh.FLAVOR = j.FLAVOR
    ORDER BY j.TOTAL_ORDER + fh.TOTAL_ORDER DESC
    LIMIT 3;